// Builds src/generator/fonts.generated.ts from @fontsource packages:
// reads the latin woff2 files for every manifest entry, base64-encodes them and
// emits a data module + `npm run build:fonts`. Commit the generated file.
//
// The data URIs serve double duty: the app injects them as @font-face rules (so canvas
// text measurement uses the real metrics) and SVG exports embed the same rules (so exports
// are WYSIWYG offline). Keep fonts OFL-licensed — they are redistributed in the bundle.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const OUT_FILE = resolve(ROOT, 'src/generator/fonts.generated.ts');

/** @type {{ pkg: string, family: string, weights: number[] }[]} */
const MANIFEST = [
    { pkg: 'patrick-hand', family: 'Patrick Hand', weights: [400] },
    { pkg: 'ibm-plex-mono', family: 'IBM Plex Mono', weights: [400] },
    { pkg: 'atkinson-hyperlegible', family: 'Atkinson Hyperlegible', weights: [400, 700] },
    { pkg: 'baloo-2', family: 'Baloo 2', weights: [600, 800] },
    { pkg: 'comic-neue', family: 'Comic Neue', weights: [400, 700] },
    { pkg: 'jost', family: 'Jost', weights: [400, 500, 600] },
    { pkg: 'fredoka', family: 'Fredoka', weights: [400, 600, 700] },
    { pkg: 'quicksand', family: 'Quicksand', weights: [400, 500] },
];

const faces = [];
for (const { pkg, family, weights } of MANIFEST) {
    for (const weight of weights) {
        const file = resolve(ROOT, `node_modules/@fontsource/${pkg}/files/${pkg}-latin-${weight}-normal.woff2`);
        let bytes;
        try {
            bytes = readFileSync(file);
        } catch {
            console.error(`Missing ${file} — run: npm install (or fix the manifest).`);
            process.exit(1);
        }
        faces.push({ family, weight, dataUri: `data:font/woff2;base64,${bytes.toString('base64')}` });
        console.log(`  ${family} ${weight}: ${(bytes.length / 1024).toFixed(1)} KB`);
    }
}

const totalKb = faces.reduce((sum, f) => sum + f.dataUri.length / 1024, 0);
const entries = faces
    .map((f) => `    { family: ${JSON.stringify(f.family)}, weight: ${f.weight}, dataUri:\n        '${f.dataUri}' },`)
    .join('\n');

const out = `/*
Generated by scripts/build-font.mjs — DO NOT EDIT BY HAND.
Regenerate with: npm run build:fonts
Sources: @fontsource packages (OFL licensed), latin subset, woff2.
*/

export interface FontFaceData {
    family: string;
    weight: number;
    /** data:font/woff2;base64,… */
    dataUri: string;
}

/** All bundled faces (~${Math.round(totalKb)} KB of base64 total). */
export const FONT_FACES: FontFaceData[] = [
${entries}
];
`;

writeFileSync(OUT_FILE, out);
console.log(`Wrote ${OUT_FILE.replace(ROOT, '.')} (${faces.length} faces, ~${Math.round(totalKb)} KB base64)`);
