// Builds src/generator/fonts.generated.ts from @fontsource packages:
// Builds the web app's font assets from @fontsource packages: reads the latin woff2 files for
// every manifest entry, copies each one to src/generator/fonts/ under a content-hashed file
// name, and emits a URL manifest (`src/generator/fonts.generated.ts`).
// Regenerate with `npm run build:fonts`. Commit the generated folder and module.
//
// The app serves fonts as static files: the injected @font-face rules point at the hashed
// URLs, so browsers cache them independently of the JS bundle — a bundle change no longer
// re-downloads ~400 KB of font bytes, and vice versa. SVG/PNG exports still embed data URIs
// (so exports are WYSIWYG offline); those are fetched from the same URLs on demand at export
// time. Keep fonts OFL-licensed — they are redistributed as files.
import { createHash } from 'node:crypto';
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const OUT_DIR = resolve(ROOT, 'src/generator/fonts');
const OUT_FILE = resolve(ROOT, 'src/generator/fonts.generated.ts');

/** @type {{ pkg: string, family: string, weights: number[] }[]} */
const MANIFEST = [
    { pkg: 'patrick-hand', family: 'Patrick Hand', weights: [400] },
    { pkg: 'ibm-plex-mono', family: 'IBM Plex Mono', weights: [400] },
    { pkg: 'atkinson-hyperlegible', family: 'Atkinson Hyperlegible', weights: [400, 700] },
    { pkg: 'baloo-2', family: 'Baloo 2', weights: [600, 800] },
    { pkg: 'comic-neue', family: 'Comic Neue', weights: [400, 700] },
    { pkg: 'jost', family: 'Jost', weights: [400, 500, 600] },
    { pkg: 'fredoka', family: 'Fredoka', weights: [400, 600, 700] },
    { pkg: 'quicksand', family: 'Quicksand', weights: [400, 500] },
    { pkg: 'montserrat', family: 'Montserrat', weights: [400, 600, 700] },
];

// Rebuild the folder from scratch so stale faces (old content hashes) don't linger.
rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const faces = [];
for (const { pkg, family, weights } of MANIFEST) {
    for (const weight of weights) {
        const file = resolve(ROOT, `node_modules/@fontsource/${pkg}/files/${pkg}-latin-${weight}-normal.woff2`);
        let bytes;
        try {
            bytes = readFileSync(file);
        } catch {
            console.error(`Missing ${file} — run: npm install (or fix the manifest).`);
            process.exit(1);
        }
        const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 10);
        const name = `${pkg}-latin-${weight}-${hash}.woff2`;
        copyFileSync(file, resolve(OUT_DIR, name));
        faces.push({ family, weight, url: `fonts/${name}`, kb: bytes.length / 1024 });
        console.log(`  ${family} ${weight}: ${faces.at(-1).kb.toFixed(1)} KB → ${name}`);
    }
}

const totalKb = faces.reduce((sum, f) => sum + f.kb, 0);
const entries = faces
    .map((f) => `    { family: ${JSON.stringify(f.family)}, weight: ${f.weight}, url: '${f.url}' },`)
    .join('\n');

const out = `/*
Generated by scripts/build-font.mjs — DO NOT EDIT BY HAND.
Regenerate with: npm run build:fonts (the woff2 files land next to this module, in fonts/).
Sources: @fontsource packages (OFL licensed), latin subset, woff2.
*/

export interface FontFaceData {
    family: string;
    weight: number;
    /** Static file served from dist/web/fonts/; the name embeds a content hash. */
    url: string;
}

/** All bundled faces (~${Math.round(totalKb)} KB of woff2, served as cacheable static files). */
export const FONT_FACES: FontFaceData[] = [
${entries}
];
`;

writeFileSync(OUT_FILE, out);
console.log(`Wrote ${OUT_FILE.replace(ROOT, '.')} + ${OUT_DIR.replace(ROOT, '.')} (${faces.length} faces, ~${Math.round(totalKb)} KB woff2)`);
