/*
Generated by scripts/build-font.mjs — DO NOT EDIT BY HAND.
Regenerate with: npm run build:fonts (the woff2 files land next to this module, in fonts/).
Sources: @fontsource packages (OFL licensed), latin subset, woff2.
*/

export interface FontFaceData {
    family: string;
    weight: number;
    /** Static file served from dist/web/fonts/; the name embeds a content hash. */
    url: string;
}

/** All bundled faces (~310 KB of woff2, served as cacheable static files). */
export const FONT_FACES: FontFaceData[] = [
    { family: "Patrick Hand", weight: 400, url: 'fonts/patrick-hand-latin-400-ac5bc9033b.woff2' },
    { family: "IBM Plex Mono", weight: 400, url: 'fonts/ibm-plex-mono-latin-400-08949f728d.woff2' },
    { family: "Atkinson Hyperlegible", weight: 400, url: 'fonts/atkinson-hyperlegible-latin-400-d64ba838ef.woff2' },
    { family: "Atkinson Hyperlegible", weight: 700, url: 'fonts/atkinson-hyperlegible-latin-700-140e2bd25a.woff2' },
    { family: "Baloo 2", weight: 600, url: 'fonts/baloo-2-latin-600-ffc22b431d.woff2' },
    { family: "Baloo 2", weight: 800, url: 'fonts/baloo-2-latin-800-3e36c57e37.woff2' },
    { family: "Comic Neue", weight: 400, url: 'fonts/comic-neue-latin-400-b7753f30f8.woff2' },
    { family: "Comic Neue", weight: 700, url: 'fonts/comic-neue-latin-700-13e9f12e3a.woff2' },
    { family: "Jost", weight: 400, url: 'fonts/jost-latin-400-f94cffda16.woff2' },
    { family: "Jost", weight: 500, url: 'fonts/jost-latin-500-98dce4f076.woff2' },
    { family: "Jost", weight: 600, url: 'fonts/jost-latin-600-d0487d6845.woff2' },
    { family: "Fredoka", weight: 400, url: 'fonts/fredoka-latin-400-9cf74f7035.woff2' },
    { family: "Fredoka", weight: 600, url: 'fonts/fredoka-latin-600-b62f2898de.woff2' },
    { family: "Fredoka", weight: 700, url: 'fonts/fredoka-latin-700-ee61b48aca.woff2' },
    { family: "Quicksand", weight: 400, url: 'fonts/quicksand-latin-400-fee25690fd.woff2' },
    { family: "Quicksand", weight: 500, url: 'fonts/quicksand-latin-500-eb8add2eff.woff2' },
    { family: "Montserrat", weight: 400, url: 'fonts/montserrat-latin-400-e66bcd2761.woff2' },
    { family: "Montserrat", weight: 600, url: 'fonts/montserrat-latin-600-d857325c36.woff2' },
    { family: "Montserrat", weight: 700, url: 'fonts/montserrat-latin-700-f9d9e65b15.woff2' },
];
